### ISSUE TITLE
Phase "Hinweis" nur beenden, wenn alle Hinweise da

### ISSUE THREAD

**Issue by ramonaranz** [stygion/LessThanTwo#2]
Die Phase "Hinweise geben", darf nur beendet werden, wenn alle Spieler einen Hinweis abgegeben haben.

Sonst kann ein solches Szenario entstehen:
![grafik](https://user-images.githubusercontent.com/63904949/79637252-0bad7180-817e-11ea-83c1-81989ea80fde.png)

Planung: Automatisch in nächste Phase springen, wenn alle Spieler einen Hinweis abgegeben haben, ohne dass der Button benötigt wird

**Comment by stygion** [comment]
Gefixt
